### ISSUE TITLE
Import All Schools at once

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#10]
Include a button to "Import All Schools" at once rather than have to individually click through the links. 

Make sure that it indicates that the schools are being imported. We need a visual indication that this is being done or else it appears that nothing is happening.

**Comment by ashish-b10** [comment]
1df6e969def8bb4f9fb48839b08dccb5d75755e0 nearly closes this.

The only thing left to do is change the "Import all schools" button to
look different when all schools are imported - it should have a
different color, say "All schools have been imported" and should no
longer submit a POST request.
