### ISSUE TITLE
"Import School" should have clearer indication that a school has been imported 

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#11]
It's a bit confusing that the button is still visible after a school has been imported. It might be intended behavior but we need to figure out what is a better indication that a school has been imported and that the user should only modify it if there are changes that need to happen.

**Comment by ashish-b10** [comment]
So we should probably keep the "Import" button as we can re-import a
school's competitor and team information. But we could change the text
to "Re-Import" instead - would that be better? And maybe we could change
the color too to distinguish the operations....
