### ISSUE TITLE
Add status information to each match.

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#16]
Similar to the system implemented by Betsy and Rae, we need to add a method for us to update the status information such as "At ring", "Holding", "Competing" because it is hard to tell what is the status of each match.

**Comment by ashish-b10** [comment]
We should add a status() function which returns a string/object representation of the status in TeamMatch

**Comment by ashish-b10** [comment]
This has been closed by 860a21fce0731e652d1c734185310766a4fa6507
