### ISSUE TITLE
Create a Docker version of the code

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#17]

**Comment by ashleywang1** [comment]
Alpine Linux 3

https://hub.docker.com/_/python/
3.6.3-alpine3.6, 3.6-alpine3.6, 3-alpine3.6, alpine3.6 (3.6/alpine3.6/Dockerfile)

Go through the setup guide automatically
- should clone the code/necessary projects
- create virtualenv with python3
- install requirements.txt
- install postgres or sqllite
- figure out the credentials (?)

**Comment by ashish-b10** [comment]
A couple things to add:

1. Definitely using PostgreSQL on the server, not SQLite. Once we have 
Docker working, installing and setting up PostgreSQL shouldn't be a 
problem. We will also need to modify pg_hba.conf to allow local 
authentication by adding something like this:

# "local" is for Unix domain socket connections only
local   all             [username]                              trust
# IPv4 local connections:
host    all             tmdb            127.0.0.1/32            trust
# IPv6 local connections:
host    all             tmdb            ::1/128                 trust

2. I forgot that there's another way to install credentials on the 
server - there's an interface through the web UI to do it. So no need to 
automate that. However, I'm not sure how we are supposed to set up a 
password for the first Django superuser. This is something we'll still 
have to figure out. Perhaps this post has some answers: 
https://stackoverflow.com/questions/22651647/docker-and-securing-passwords

3. We will also need to install Redis as it's required for Django 
channels to work, and we'll have to set up Django channels as well. This 
portion of the setup not included in the documentation, unfortunately.

4. Once this is all working, and all of our developers have migrated to 
Docker, we should probably remove everything in the ectc_tm_server 
directory and create a setup.py file. But this will probably be taken 
care of in a separate ticket.

**Comment by ashleywang1** [comment]
The Docker version is here: https://github.com/ashleywang1/ECTC_tournament_manager 

Notes:

- alpine OS packaging is done via 'apk add'
- The start.sh file creates the data directory tmdb in the folder tmdb_data as user postgres.
- ectc_tm_server/settings.py needs to have the following variable:
#from .db_settings import DATABASES
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'tmdb',
        'USER': 'postgres',
    }
}
And in the future, this file should be generated automatically.

**Comment by ashleywang1** [comment]
This has been done - https://github.com/ashleywang1/ECTC_tournament_manager
