### ISSUE TITLE
wrap long school names

### ISSUE THREAD

**Issue by edavidaja** [ashish-b10/tournament_manager#31]
otherwise they overflow the match sheet boxes.

textwrap, maybe?

**Comment by ashish-b10** [comment]
I don't think reportlab (middleware we're using to draw text fields on the PDF) supports wrapping of text fields. But a quick search here suggests one way that might work:

http://stackoverflow.com/questions/4726011/wrap-text-in-a-table-reportlab

**Comment by ashish-b10** [comment]
The best way to do this is to add a column in the registration dashboard on the schools tab. The column should be a short name for the school. This will ensure that everybody's database is uniform in terms of the school's short name and saves effort from having to write a UI to support it.

@darknessrises88 is this something we can do?

**Comment by darknessrises88** [comment]
This existed for all of half a tournament, but broke :p I'll take another look at it and fix it so that it works reliably.

**Comment by aguatemala** [comment]
lol I'm happy to also add it/maintain it from our side! Just might need to make sure you are reading from the right column from now on! Thanks, Tara!

**Comment by ashish-b10** [comment]
Awesome, thanks! Let us know when it's done, cause we might have to make some updates to the script we use to import the schools.

**Comment by darknessrises88** [comment]
I'll work on it this weekend

**Comment by aguatemala** [comment]
Mostly done here. We are now using shorter namse
