### ISSUE TITLE
Export seeds

### ISSUE THREAD

**Issue by ashish-b10** [ashish-b10/tournament_manager#33]
It would be helpful if we can export seeds in a format that we can easily paste into Tara's spreadsheet and into Challonge as well.

Let's add an export seeds button on the seedings page. Clicking on the export link should return a document that looks something like:

```
Seeds for Men's A team:
1<tab>MIT A1 (LMH)
2<tab>Cornell A1(LMH)
3<tab>MIT A2 (LMH)
```

Using tabs as column delimiters and new lines as row delimiters will allow for easy pasting into a Google spreadsheet.

The returned document should be plain text. In other words, the view should return something like,

```python
seedings = #generate the formatted string in the quote above
HttpResponse(seedings, content_type="text/plain")
```

**Comment by ashish-b10** [comment]
@edavidaja is this a convenient format for creating the bracket in challonge too?

**Comment by edavidaja** [comment]
Yes, with one provision: it should return rows where seeds have been skipped within one-person team, as in
```
31 Rutgers Men's A-team4 (L):  
32 Brown Men's A-team1 (L):  
33 [blank1]  
34 [blank2]  
35 [blank3]  
36 U Mich Men's A-team3 (M):  
```
and challonge requires unique entries so it's preferable if they're numbered.

**Comment by aguatemala** [comment]
@edavidaja 
Should they be _blank_ or have a "bye"?

**Comment by edavidaja** [comment]
Sorry, that was unclear: they should have a "bye", and the entries have to be unique so they should be "bye1", "bye2", etc.

**Comment by aguatemala** [comment]
This is what I have. Does this work? 

```Women's B Seeds:
1	MIT Women's B1(LMH)
2	Tufts Women's B1(LMH)
3	Cornell Women's B1(LMH)
4	Cornell Women's B2(LMH)
5	Brown Women's B1(LM)
6	Columbia Women's B1(LMH)
7	U Conn Women's B1(MH)
8	West Point Women's B1(MH)
9	U Albany Women's B1(MH)
10	BU Women's B1(LMH)
11	UVM Women's B1(MH)
12	Tufts Women's B2(MH)
13	Brown Women's B2(L)
14	Dartmouth Women's B1(H)
15	MIT Women's B2(M)
16	Rutgers Women's B1(L)
17	bye17
18	bye18
19	bye19
20	bye20
21	bye21
22	bye22
23	bye23
24	bye24
25	bye25
26	bye26
27	bye27
28	bye28
29	bye29
30	bye30
31	bye31
32	bye32
33	bye33
34	bye34
35	bye35
36	bye36
37	bye37
38	bye38
39	bye39
40	bye40
41	bye41
42	bye42
43	bye43
44	bye44
45	bye45
46	bye46
47	bye47
48	bye48
49	bye49
50	bye50
51	bye51
52	bye52
53	bye53
54	bye54
55	bye55
56	bye56
57	bye57
58	bye58
59	bye59
60	bye60
61	bye61
62	bye62
63	bye63
64	bye64

**Comment by edavidaja** [comment]
Further clarification: byes need to be inserted between _non-contiguous seeds_, as in the example I posted above, but not at the end.

**Comment by aguatemala** [comment]
Got it! I removed stuff after the last seed. 

```Women's A Seeds:
1	Cornell Women's A1 (LMH)
2	MIT Women's A1 (LMH)
3	Rutgers Women's A1 (LMH)
4	Columbia Women's A1 (LMH)
5	Tufts Women's A1 (LH)
6	Columbia Women's A2 (LM)
7	Cornell Women's A2 (LMH)
8	BU Women's A1 (LH)
9	Northeastern Women's A1 (LH)
10	NYU Women's A1 (MH)
11	Dartmouth Women's A1 (M)
12	Cortland Women's A1 (H)
13	U Albany Women's A1 (M)
14	bye14
15	Harvard Women's A1 (L)
16	West Point Women's A1 (M)

**Comment by edavidaja** [comment]
👍

**Comment by aguatemala** [comment]
We are not using challonge anymore so I am closing this ticket
