### ISSUE TITLE
Match List Colours and sticky header

### ISSUE THREAD

**Issue by aguatemala** [ashish-b10/tournament_manager#42]
Use colours from the old spreadsheet in the match list view and re-enable the sticky header

**Comment by ashish-b10** [comment]
Actually, I ended up changing green to lightgreen. Here are the before and after, let me know what you think:
![screenshot_2018-02-11_12-12-03](https://user-images.githubusercontent.com/15025764/36076033-f717d13e-0f24-11e8-9441-6d3c23e5da47.png)
![screenshot_2018-02-11_12-12-13](https://user-images.githubusercontent.com/15025764/36076034-f75ddee0-0f24-11e8-9afb-b10bbf9783b8.png)

**Comment by ashish-b10** [comment]
here are better screenshots:

![screenshot_2018-02-11_12-14-19](https://user-images.githubusercontent.com/15025764/36076042-2106b76c-0f25-11e8-8f90-51cb12067f52.png)
![Uploading Screenshot_2018-02-11_12-14-25.png…]()

**Comment by ashish-b10** [comment]
Uploading the last one was too hard, eh

![screenshot_2018-02-11_12-14-25](https://user-images.githubusercontent.com/15025764/36076886-a5ffac84-0f30-11e8-930b-c16408defc58.png)

**Comment by ashish-b10** [comment]
I can't remember why I reopened this but it looks fine to me. Closing it now.
