### ISSUE TITLE
Match list view - Better way of displaying status

### ISSUE THREAD

**Issue by aguatemala** [ashish-b10/tournament_manager#45]
* Remove multiple checkboxes and replace with a dropdown menu
* Add a competing status - add correct colour too

**Comment by aguatemala** [comment]
Valid statuses:
- Empty
- At holding
- At ring
- Competing

**Comment by ashish-b10** [comment]
Adding the competing status is similar to this commit:

https://github.com/ashish-b10/tournament_manager/commit/2722bad5f846d86d458d97afb5286e6e99b2d583
