### ISSUE TITLE
Bracket view

### ISSUE THREAD

**Issue by ashish-b10** [ashish-b10/tournament_manager#5]
Create a view that takes all the matches in a division and displays them in a bracket view.

A sample of what the bracket could look like is here: http://ashishbanerjee.net/bracket/sample_bracket.html

**Comment by mwchen** [comment]
Possible ideas:
https://www.bracketsninja.com/?orig=true
http://api.challonge.com/v1
http://api.challonge.com/v1/documents/jquery
https://github.com/russ-/pychallonge

**Comment by ashish-b10** [comment]
This has been complete since before MIT 2016
