### ISSUE TITLE
Match list view - Remove print button

### ISSUE THREAD

**Issue by aguatemala** [ashish-b10/tournament_manager#58]
Remove the print match sheet button. Instead, make it a link on the match number.

**Comment by mwchen** [comment]
I accidentally merged this directly into master because of my branch 58 was in a weird state with the old master Docker files. 

Here is the diff: https://github.com/ashish-b10/tournament_manager/compare/0d1777c...master

**Comment by mwchen** [comment]
Changes that were made: 
- Limit the ring number to 1-7. 
- Ensure the consistent width of the school name (which might mean that certain schools could be cut off).
- Comment out the print button for now for the matches. 
- Remove some of the extra code that would allow for something to show up before the javascript code for the websocket showed up.

**Comment by mwchen** [comment]
Open question: 
- Where is the Print Match Sheets suppose to live?

**Comment by aguatemala** [comment]
Answer: Putting in a new ticket to move the individual match sheet functionality. This is good for now. Thanks, Machine 🥇
