### ISSUE TITLE
Store Settings

### ISSUE THREAD

**Issue by mwchen** [ashish-b10/tournament_manager#9]
Currently, it is a pain to have to add the secret_key after the models change (and the database is dropped). 

We should have a cleaner way of storing settings.

**Comment by ashish-b10** [comment]
I can think of a few ways to do this, but I think the simplest would be
to create a script in tmdb/management/commands/ which will import the
key. Something like 'python manage.py import_gdrive_key
/path/to/credentials.json' - then we could add that to the reset_db.sh
script.

Another way we could do it would be to cache a key in the user's home
directory (say, ~/.tmdb/credentials.json) and load it automatically, but
this is a little too transparent for my taste...
